name: Generate Snake Animation

on:
  schedule: # Har kuni avtomatik ishga tushadi
    - cron: "0 0 * * *"
  workflow_dispatch: # Qo‘lda ham ishga tushirish mumkin

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      # Repositoryni klonlash
      - name: Checkout
        uses: actions/checkout@v3

      # Snake.js ishlatish
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: sotvoldiyew
          outputs: svg

      # GitHub Pages’ga chiqarish
      - name: Push to GitHub
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: output
          build_dir: .github/snake
